// <auto-generated />
using System;
using AsikaGo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AsikaGo.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928013430_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.BusinessCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_business_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_business_categories_name");

                    b.ToTable("business_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Description = "Restaurants, cafes, and food stalls.",
                            Name = "Food and Beverage"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Description = "Selling goods directly to consumers.",
                            Name = "Retail"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            Description = "Offering skills or labor rather than goods.",
                            Name = "Services"
                        });
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.BusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("business_type");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registration_status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_business_profiles");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_business_profiles_category_id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_business_profiles_city_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_business_profiles_user_id");

                    b.ToTable("business_profiles", (string)null);
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_name");

                    b.ToTable("cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Name = "Quezon City",
                            Region = "NCR"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Name = "Manila",
                            Region = "NCR"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Name = "Pasig",
                            Region = "NCR"
                        });
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymous");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.RegistrationStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_registration_steps");

                    b.ToTable("registration_steps", (string)null);
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.Requirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.HasKey("Id")
                        .HasName("pk_requirements");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_requirements_source_id");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_requirements_step_id");

                    b.ToTable("requirements", (string)null);
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.RequirementProgress", b =>
                {
                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_id");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_prepared");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoadmapId", "RequirementId")
                        .HasName("pk_requirement_progress");

                    b.HasIndex("RequirementId")
                        .HasDatabaseName("ix_requirement_progress_requirement_id");

                    b.ToTable("requirement_progress", (string)null);
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.RoadmapProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.HasKey("Id")
                        .HasName("pk_roadmap_progress");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_roadmap_progress_step_id");

                    b.HasIndex("RoadmapId", "StepId")
                        .IsUnique()
                        .HasDatabaseName("ix_roadmap_progress_roadmap_id_step_id");

                    b.ToTable("roadmap_progress", (string)null);
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.RoadmapRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("effect");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.HasKey("Id")
                        .HasName("pk_roadmap_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_roadmap_rules_category_id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_roadmap_rules_city_id");

                    b.HasIndex("RequirementId")
                        .HasDatabaseName("ix_roadmap_rules_requirement_id");

                    b.HasIndex("StepId")
                        .HasDatabaseName("ix_roadmap_rules_step_id");

                    b.ToTable("roadmap_rules", (string)null);
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.SourceReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DateVerified")
                        .HasColumnType("date")
                        .HasColumnName("date_verified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_source_references");

                    b.ToTable("source_references", (string)null);
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.UserRoadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_user_roadmaps");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_user_roadmaps_business_id");

                    b.ToTable("user_roadmaps", (string)null);
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.BusinessProfile", b =>
                {
                    b.HasOne("AsikaGo.Api.Data.Entities.BusinessCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_business_profiles_business_categories_category_id");

                    b.HasOne("AsikaGo.Api.Data.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_business_profiles_cities_city_id");

                    b.HasOne("AsikaGo.Api.Data.Entities.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_profiles_profiles_user_id");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.Requirement", b =>
                {
                    b.HasOne("AsikaGo.Api.Data.Entities.SourceReference", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_requirements_source_references_source_id");

                    b.HasOne("AsikaGo.Api.Data.Entities.RegistrationStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requirements_registration_steps_step_id");

                    b.Navigation("Source");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.RequirementProgress", b =>
                {
                    b.HasOne("AsikaGo.Api.Data.Entities.Requirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_requirement_progress_requirements_requirement_id");

                    b.HasOne("AsikaGo.Api.Data.Entities.UserRoadmap", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requirement_progress_user_roadmaps_roadmap_id");

                    b.Navigation("Requirement");

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.RoadmapProgress", b =>
                {
                    b.HasOne("AsikaGo.Api.Data.Entities.UserRoadmap", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roadmap_progress_user_roadmaps_roadmap_id");

                    b.HasOne("AsikaGo.Api.Data.Entities.RegistrationStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roadmap_progress_registration_steps_step_id");

                    b.Navigation("Roadmap");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.RoadmapRule", b =>
                {
                    b.HasOne("AsikaGo.Api.Data.Entities.BusinessCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roadmap_rules_business_categories_category_id");

                    b.HasOne("AsikaGo.Api.Data.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roadmap_rules_cities_city_id");

                    b.HasOne("AsikaGo.Api.Data.Entities.Requirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roadmap_rules_requirements_requirement_id");

                    b.HasOne("AsikaGo.Api.Data.Entities.RegistrationStep", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roadmap_rules_registration_steps_step_id");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("Requirement");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("AsikaGo.Api.Data.Entities.UserRoadmap", b =>
                {
                    b.HasOne("AsikaGo.Api.Data.Entities.BusinessProfile", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roadmaps_business_profiles_business_id");

                    b.Navigation("Business");
                });
#pragma warning restore 612, 618
        }
    }
}
