/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnonymousTypeOfstring"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/business-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessProfileResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveBusinessProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BusinessProfileResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessment/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssessmentOptionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roadmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoadmapResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roadmap/steps/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    number: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RoadmapStepResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnonymousTypeOfstring: {
            status: null | string;
        };
        AssessmentOptionsResponse: {
            categories: components["schemas"]["CategoryOption"][];
            businessTypes: string[];
            registrationStatuses: string[];
        };
        BusinessProfileResponse: {
            /** Format: uuid */
            id: string;
            businessName: null | string;
            businessType: string;
            /** Format: uuid */
            categoryId: string;
            categoryName: string;
            /** Format: uuid */
            cityId: string;
            cityName: string;
            registrationStatus: components["schemas"]["RegistrationStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        CategoryOption: {
            /** Format: uuid */
            id: string;
            name: string;
            description: null | string;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            email: null | string;
            isAnonymous: boolean;
        };
        /** @enum {unknown} */
        RegistrationStatus: "Planning" | "Started";
        RequirementResponse: {
            /** Format: uuid */
            id: string;
            text: string;
            source: components["schemas"]["SourceResponse"];
        };
        RoadmapResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            steps: components["schemas"]["RoadmapStepResponse"][];
        };
        RoadmapStepResponse: {
            /** Format: int32 */
            number: number | string;
            title: string;
            description: string;
            status: components["schemas"]["StepStatus"];
            requirements: components["schemas"]["RequirementResponse"][];
            /** Format: int32 */
            estimatedHours: number | string;
        };
        SaveBusinessProfileRequest: {
            businessName: null | string;
            businessType: string;
            /** Format: uuid */
            categoryId: string;
            registrationStatus: null | components["schemas"]["RegistrationStatus"];
        };
        SourceResponse: {
            type: string;
            description: string;
        };
        /** @enum {unknown} */
        StepStatus: "Planned" | "Started" | "Completed" | "Locked";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
